[workspace]
members = [
    "chapter03-common-programming-concepts",
    "chapter04-understanding-ownership",
    "chapter05-using-structs-to-structure-related-data",
    "chapter06-enums-and-pattern-matching",
    "chapter07-managing-growing-projects-with-packages-crates-and-modules",
    "chapter08-common-collections",
    "chapter09-error-handling",
    "chapter10-generic-types-traits-and-lifetimes",
    "chapter11-writing-automated-tests",
    "chapter12-an-i-o-project-building-a-command-line-program",
    "chapter13-functional-language-features-iterators-and-closures",
    "chapter14-more-about-cargo-and-crates-io",
    "chapter15-smart-pointers",
    "chapter16-fearless-concurrency",
    "chapter17-fundamentals-of-asynchronous-programming",
    "chapter18-object-oriented-programming-features-of-rust",
    "chapter19-patterns-and-matching",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"
